#!/usr/bin/env node
'use strict';
/* Storyteller d10 generic room server v0.7.7-alpha
 * Server owns room/session authority and shared tactical state only.
 * It deliberately contains no game-specific Traits, dice, damage formulas, or movement formulas.
 */
const http=require('http');
const crypto=require('crypto');
const PORT=Number(process.env.PORT||8787),HOST=process.env.HOST||'0.0.0.0',PROTOCOL=23,VERSION='0.7.7-alpha';
const MAX_PAYLOAD=Number(process.env.MAX_PAYLOAD||5*1024*1024),MAX_ASSET_DATA=Number(process.env.MAX_ASSET_DATA||3_700_000),MAX_ROOM_ASSETS=Number(process.env.MAX_ROOM_ASSETS||120),MAX_LOG=Number(process.env.MAX_LOG||300),ROOM_TTL_MS=Number(process.env.ROOM_TTL_MS||12*60*60*1000),ALLOWED_ORIGINS=String(process.env.ALLOWED_ORIGINS||'').split(',').map(s=>s.trim()).filter(Boolean);
const rooms=new Map();
const now=()=>Date.now();
const clone=(x,f=null)=>{try{return JSON.parse(JSON.stringify(x))}catch{return f}};
const text=(v,n=500)=>String(v??'').slice(0,n);
const num=(v,min,max,f=0)=>{v=Number(v);return Number.isFinite(v)?Math.max(min,Math.min(max,v)):f};
const iid=(p='id')=>`${p}:${crypto.randomUUID()}`;
const clientId=v=>text(v,128).replace(/[^a-zA-Z0-9:_-]/g,'');
const actorId=v=>text(v,180).replace(/[^a-zA-Z0-9:_-]/g,'');
const roomCode=v=>text(v,8).toUpperCase().replace(/[^A-Z2-9]/g,'');
function makeCode(){const abc='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';for(let z=0;z<100;z++){let s='';for(let i=0;i<6;i++)s+=abc[crypto.randomInt(abc.length)];if(!rooms.has(s))return s;}throw new Error('Unable to allocate room code');}
function blankSessionTools(){return{checkRequests:[],sharedRolls:[],updatedAt:now()}}
function cleanCheckRequest(x={}){const answer=x.answer&&typeof x.answer==='object'?x.answer:null;return{id:actorId(x.id)||iid('check'),targetClientId:clientId(x.targetClientId),targetActorId:actorId(x.targetActorId),label:text(x.label||'Requested check',160),attribute:text(x.attribute,80),ability:text(x.ability,80),difficulty:num(x.difficulty,0,20,0),situational:num(x.situational,-20,20,0),specialty:!!x.specialty,note:text(x.note,500),status:['open','answered','dismissed'].includes(x.status)?x.status:'open',requestedBy:clientId(x.requestedBy),requestedAt:num(x.requestedAt,0,Number.MAX_SAFE_INTEGER,now()),answeredAt:x.answeredAt==null?null:num(x.answeredAt,0,Number.MAX_SAFE_INTEGER,0),answer:answer?{text:text(answer.text,1200),source:text(answer.source||'client',40),actorId:actorId(answer.actorId),at:num(answer.at,0,Number.MAX_SAFE_INTEGER,now())}:null}}
function cleanSharedRoll(x={}){return{id:actorId(x.id)||iid('roll'),clientId:clientId(x.clientId),name:text(x.name||'Player',120),label:text(x.label||'Shared roll',160),count:num(x.count,1,100,1),sides:num(x.sides,2,100,10),results:Array.isArray(x.results)?x.results.slice(0,100).map(v=>num(v,1,100,1)):[],at:num(x.at,0,Number.MAX_SAFE_INTEGER,now())}}
function point(p){return{x:num(p?.x,-100000,100000,0),y:num(p?.y,-100000,100000,0)}}
function wall(w){return{id:actorId(w?.id)||iid('wall'),kind:'wall',ownerId:clientId(w?.ownerId),x1:num(w?.x1,-100000,100000,0),y1:num(w?.y1,-100000,100000,0),x2:num(w?.x2,-100000,100000,0),y2:num(w?.y2,-100000,100000,0),label:text(w?.label,80),at:num(w?.at,0,Number.MAX_SAFE_INTEGER,now())}}
function zone(z){const d=z?.duration&&typeof z.duration==='object'?z.duration:{};return{id:actorId(z?.id)||iid('zone'),kind:'zone',ownerId:clientId(z?.ownerId),shape:['rect','circle'].includes(z?.shape)?z.shape:'rect',x1:num(z?.x1,-100000,100000,0),y1:num(z?.y1,-100000,100000,0),x2:num(z?.x2,-100000,100000,0),y2:num(z?.y2,-100000,100000,0),zoneType:['hazard','cover','rough','note','field'].includes(z?.zoneType)?z.zoneType:'note',label:text(z?.label,120),sourceId:text(z?.sourceId,180),sourceKind:text(z?.sourceKind,80),sourceActorId:actorId(z?.sourceActorId),active:z?.active!==false,tags:Array.isArray(z?.tags)?z.tags.slice(0,40).map(v=>text(v,80)):[],duration:{kind:text(d.kind||z?.durationKind||'special',40),startedRound:d.startedRound==null?null:num(d.startedRound,0,99999,0),expiresRound:d.expiresRound==null?null:num(d.expiresRound,0,99999,0),sceneId:text(d.sceneId,180),expiresAt:d.expiresAt==null?null:num(d.expiresAt,0,Number.MAX_SAFE_INTEGER,0)},effect:clone(z?.effect,{}),data:clone(z?.data,{}),at:num(z?.at,0,Number.MAX_SAFE_INTEGER,now())}}
function topo(z){const shape=z?.shape==='poly'?'poly':'rect';return{id:actorId(z?.id)||iid('topo'),kind:'topography',ownerId:clientId(z?.ownerId),shape,name:text(z?.name||'Topography',100),x1:num(z?.x1,-100000,100000,0),y1:num(z?.y1,-100000,100000,0),x2:num(z?.x2,-100000,100000,0),y2:num(z?.y2,-100000,100000,0),points:shape==='poly'&&Array.isArray(z?.points)?z.points.slice(0,100).map(point):[],baseElevation:num(z?.baseElevation,-10000,10000,0),height:num(z?.height,0,10000,0),surfaceMode:z?.surfaceMode==='slope'?'slope':'flat',slopeDirection:['north','south','east','west'].includes(z?.slopeDirection)?z.slopeDirection:'east',topOccupiable:z?.topOccupiable!==false,blockMovement:!!z?.blockMovement,blockSight:!!z?.blockSight,checkRequired:!!z?.checkRequired,check:{label:text(z?.check?.label||z?.name||'Traversal',100),attribute:text(z?.check?.attribute,80),ability:text(z?.check?.ability,80),difficulty:num(z?.check?.difficulty,0,20,0),situational:num(z?.check?.situational,-20,20,0)},at:num(z?.at,0,Number.MAX_SAFE_INTEGER,now())}}
function drawing(d){return{id:actorId(d?.id)||iid('draw'),kind:'drawing',ownerId:clientId(d?.ownerId),points:Array.isArray(d?.points)?d.points.slice(0,160).map(point):[],at:num(d?.at,0,Number.MAX_SAFE_INTEGER,now())}}
function template(t){return{id:actorId(t?.id)||iid('template'),kind:'template',ownerId:clientId(t?.ownerId),shape:['circle','cone','line','square'].includes(t?.shape)?t.shape:'circle',x1:num(t?.x1,-100000,100000,0),y1:num(t?.y1,-100000,100000,0),x2:num(t?.x2,-100000,100000,0),y2:num(t?.y2,-100000,100000,0),label:text(t?.label,80),at:num(t?.at,0,Number.MAX_SAFE_INTEGER,now())}}
const SYSTEM_ACCESS_LEVELS=['none','read','operate','admin','root'];
function systemRecord(x,kind='record'){x=x&&typeof x==='object'?x:{};const d=x.duration&&typeof x.duration==='object'?x.duration:{};return{id:actorId(x.id)||iid(`system-${kind}`),kind:text(x.kind||kind,80),actorId:actorId(x.actorId||x.sourceActorId),sourceId:text(x.sourceId,180),sourceActorId:actorId(x.sourceActorId||x.actorId),level:SYSTEM_ACCESS_LEVELS.includes(String(x.level||'none').toLowerCase())?String(x.level||'none').toLowerCase():'none',strength:num(x.strength,0,10000,0),active:x.active!==false,duration:{kind:text(d.kind||'special',40),startedRound:d.startedRound==null?null:num(d.startedRound,0,99999,0),expiresRound:d.expiresRound==null?null:num(d.expiresRound,0,99999,0),sceneId:text(d.sceneId,180),expiresAt:d.expiresAt==null?null:num(d.expiresAt,0,Number.MAX_SAFE_INTEGER,0)},data:clone(x.data,{}),createdAt:num(x.createdAt,0,Number.MAX_SAFE_INTEGER,now())}}
function worldSystem(x){if(!x||typeof x!=='object')return null;return{kind:text(x.kind||'machine',80),enabled:x.enabled!==false,online:x.online!==false,networkId:text(x.networkId,180),securityRating:num(x.securityRating,0,20,0),resistanceRating:num(x.resistanceRating??x.effectiveStamina,0,100,0),perceptionRating:num(x.perceptionRating,0,100,0),controlResistance:num(x.controlResistance,0,100,0),robustnessDifficulty:num(x.robustnessDifficulty,0,20,0),programDifficulty:num(x.programDifficulty??x.securityRating,0,20,0),shieldRating:num(x.shieldRating,0,100,0),hardwareProfile:text(x.hardwareProfile,240),softwareProfile:text(x.softwareProfile,240),defaultHardwareProfile:text(x.defaultHardwareProfile??x.hardwareProfile,240),defaultSoftwareProfile:text(x.defaultSoftwareProfile??x.softwareProfile,240),storageState:['normal','erased','corrupted'].includes(x.storageState)?x.storageState:'normal',dataRevision:num(x.dataRevision,0,Number.MAX_SAFE_INTEGER,0),programRevision:num(x.programRevision,0,Number.MAX_SAFE_INTEGER,0),customizationRevision:num(x.customizationRevision,0,Number.MAX_SAFE_INTEGER,0),configuration:clone(x.configuration,{}),defaultConfiguration:clone(x.defaultConfiguration??x.configuration,{}),access:Array.isArray(x.access)?x.access.slice(0,100).map(v=>systemRecord(v,'access')):[],daemons:Array.isArray(x.daemons)?x.daemons.slice(0,100).map(v=>systemRecord(v,'daemon')):[],overrides:Array.isArray(x.overrides)?x.overrides.slice(0,100).map(v=>systemRecord(v,'override')):[],marks:Array.isArray(x.marks)?x.marks.slice(0,100).map(v=>systemRecord(v,'mark')):[],data:clone(x.data,{})}}
const MUTABLE_OBJECT_KEYS=['material','form','massKg','sizeClass','complexity','soak','tags','properties','footprint'];
function mutationDuration(d={}){d=d&&typeof d==='object'?d:{};return{kind:text(d.kind||'special',40),startedRound:d.startedRound==null?null:num(d.startedRound,0,99999,0),expiresRound:d.expiresRound==null?null:num(d.expiresRound,0,99999,0),sceneId:text(d.sceneId||'',180),expiresAt:d.expiresAt==null?null:num(d.expiresAt,0,Number.MAX_SAFE_INTEGER,0)}}
function objectMutation(m){m=m&&typeof m==='object'?m:{};return{id:actorId(m.id||iid('mutation')),sourceId:text(m.sourceId||'',180),sourceKind:text(m.sourceKind||'effect',80),sourceActorId:actorId(m.sourceActorId),label:text(m.label||'Mutation',160),active:m.active!==false,order:num(m.order??m.createdAt??now(),0,Number.MAX_SAFE_INTEGER,now()),duration:mutationDuration(m.duration||{}),patch:clone(m.patch,{}),data:clone(m.data,{}),createdAt:num(m.createdAt||now(),0,Number.MAX_SAFE_INTEGER,now())}}
function mutationSnapshot(o){const x={};for(const k of MUTABLE_OBJECT_KEYS)x[k]=clone(o[k],null);return x}
function mergeMutationPatch(base,patch){const out=clone(base,{});for(const k of MUTABLE_OBJECT_KEYS){if(!(k in (patch||{})))continue;if(k==='properties')out.properties={...(out.properties||{}),...clone(patch.properties,{})};else if(k==='footprint')out.footprint={...(out.footprint||{}),...clone(patch.footprint,{})};else out[k]=clone(patch[k],null)}return out}
function rebuildMutations(o){if(!o?.mutationBase)return o;let st=clone(o.mutationBase,{});for(const m of[...(o.mutations||[])].filter(x=>x.active!==false).sort((a,b)=>(a.order||0)-(b.order||0)))st=mergeMutationPatch(st,m.patch);for(const k of MUTABLE_OBJECT_KEYS)if(k in st)o[k]=clone(st[k],null);return o}
function worldObject(o={}){o=o&&typeof o==='object'?o:{};const hp=o.health&&typeof o.health==='object'?o.health:{},d=o.duration&&typeof o.duration==='object'?o.duration:{},c=o.control&&typeof o.control==='object'?o.control:{},cd=c.duration&&typeof c.duration==='object'?c.duration:{},f=o.footprint&&typeof o.footprint==='object'?o.footprint:{},max=Math.max(0,num(hp.max??o.healthLevels,0,100000,0)),cur=Math.max(0,Math.min(max,num(hp.current??max,0,100000,max))),out={id:actorId(o.id||iid('object')),kind:'object',ownerId:clientId(o.ownerId),sourceId:text(o.sourceId,180),sourceKind:text(o.sourceKind,80),sourceActorId:actorId(o.sourceActorId),name:text(o.name||'Object',160),objectType:text(o.objectType||'object',80),material:text(o.material,120),form:text(o.form,160),position:point(o.position),footprint:{cols:num(f.cols,.1,100,1),rows:num(f.rows,.1,100,1)},massKg:num(o.massKg,0,1e12,0),sizeClass:text(o.sizeClass,80),complexity:num(o.complexity,0,20,0),soak:num(o.soak,0,10000,0),health:{current:cur,max},state:['intact','damaged','disabled','destroyed','transformed'].includes(o.state)?o.state:(cur<=0?'destroyed':cur<max?'damaged':'intact'),active:o.active!==false,tags:Array.isArray(o.tags)?o.tags.slice(0,60).map(x=>text(x,80)):[],properties:clone(o.properties,{}),mutationBase:o.mutationBase&&typeof o.mutationBase==='object'?clone(o.mutationBase,{}):null,mutations:Array.isArray(o.mutations)?o.mutations.slice(0,100).map(objectMutation):[],forces:Array.isArray(o.forces)?o.forces.slice(0,100).map(forceRecord):[],control:{actorId:actorId(c.actorId),mode:text(c.mode,80),might:num(c.might,0,10000,0),sourceId:text(c.sourceId,180),sourceActorId:actorId(c.sourceActorId||c.actorId),duration:mutationDuration(cd)},system:worldSystem(o.system),duration:mutationDuration(d),data:clone(o.data,{}),createdAt:num(o.createdAt||now(),0,Number.MAX_SAFE_INTEGER,now()),updatedAt:num(o.updatedAt||now(),0,Number.MAX_SAFE_INTEGER,now())};return rebuildMutations(out)}

const FORCE_MODES=['hold','move','attract','repel','throw','crush','guide'];
function forceRecord(f={}){f=f&&typeof f==='object'?f:{};const d=f.duration&&typeof f.duration==='object'?f.duration:{},v=f.vector&&typeof f.vector==='object'?f.vector:{},a=f.anchorPoint&&typeof f.anchorPoint==='object'?point(f.anchorPoint):null,t=f.targetPoint&&typeof f.targetPoint==='object'?point(f.targetPoint):null;let vx=num(v.x,-1,1,0),vy=num(v.y,-1,1,0),vl=Math.hypot(vx,vy);if(vl>1e-7){vx/=vl;vy/=vl}else{vx=0;vy=0}return{id:actorId(f.id)||iid('force'),sourceId:text(f.sourceId,180),sourceKind:text(f.sourceKind||'effect',80),sourceActorId:actorId(f.sourceActorId),label:text(f.label||'Force',160),active:f.active!==false,mode:FORCE_MODES.includes(String(f.mode||'move').toLowerCase())?String(f.mode||'move').toLowerCase():'move',vector:{x:vx,y:vy},anchorPoint:a,targetPoint:t,liftSuccesses:num(f.liftSuccesses,0,1000,0),capacityKg:num(f.capacityKg,0,1e15,0),speedPerAction:num(f.speedPerAction,0,1e9,0),effectiveMight:num(f.effectiveMight,0,10000,0),duration:mutationDuration(d),data:clone(f.data,{}),createdAt:num(f.createdAt||now(),0,Number.MAX_SAFE_INTEGER,now())}}
function upsertForceList(xs,f){const x=forceRecord(f),out=Array.isArray(xs)?xs.slice():[],i=out.findIndex(v=>v.id===x.id);if(i>=0)out[i]=x;else out.push(x);return out.slice(-100)}
function forceTarget(r,kind,id){if(kind==='object')return r.table.world.objects.find(o=>o.id===id)||null;if(kind==='actor')return r.table.encounter.actors.find(a=>a.id===id)||null;return null}
function forcePos(r,kind,id){if(kind==='object')return r.table.world.objects.find(o=>o.id===id)?.position||null;if(kind==='actor')return r.table.positions[id]||null;return null}
function setForcePos(r,kind,id,p){p=point(p);const m=r.table.map,w=(m.columns||30)*(m.gridSize||64),h=(m.rows||18)*(m.gridSize||64),q={x:Math.max(0,Math.min(w,p.x)),y:Math.max(0,Math.min(h,p.y))};if(kind==='object'){const o=r.table.world.objects.find(x=>x.id===id);if(!o)return false;o.position=q;o.updatedAt=now()}else if(kind==='actor'){if(!r.table.encounter.actors.some(a=>a.id===id))return false;r.table.positions[id]=q}else return false;return true}
function displaceForce(r,kind,id,f,destination){const from=forcePos(r,kind,id);if(!from||!destination)return{moved:false,distance:0,blocked:false,position:from?clone(from,{}):null};const x=forceRecord(f),to=point(destination),dist=distance2d(r.table.map,from,to);if(dist<=1e-7)return{moved:false,distance:0,blocked:false,position:clone(from,{})};const max=Math.max(0,Number(x.speedPerAction)||0),travel=Math.min(dist,max||dist),ratio=travel/dist,next={x:from.x+(to.x-from.x)*ratio,y:from.y+(to.y-from.y)*ratio},wall=routeCrossesWall(r.table.map,from,next),gate=topologyGate(r.table.map,from,next);if(wall||gate?.kind==='blocked')return{moved:false,distance:0,blocked:true,position:clone(from,{}),reason:wall?'wall':'topography'};setForcePos(r,kind,id,next);return{moved:true,distance:travel,blocked:false,position:clone(next,{})}}
function upsertForce(r,kind,id,f,destination=null){const target=forceTarget(r,kind,id);if(!target)return false;const x=forceRecord(f);if(kind==='object'){const o=worldObject(target);o.forces=upsertForceList(o.forces,x);upsertWorldObject(r,o)}else{const i=r.table.encounter.actors.findIndex(a=>a.id===id),a=actor(target);a.forces=upsertForceList(a.forces,x);r.table.encounter.actors[i]=a}if(destination)displaceForce(r,kind,id,x,destination);return true}
function removeForce(r,kind,id,forceId){const target=forceTarget(r,kind,id);if(!target)return false;const xs=Array.isArray(target.forces)?target.forces:[],next=xs.filter(x=>x.id!==forceId);if(next.length===xs.length)return false;if(kind==='object'){const o=worldObject(target);o.forces=next;upsertWorldObject(r,o)}else{const i=r.table.encounter.actors.findIndex(a=>a.id===id),a=actor(target);a.forces=next;r.table.encounter.actors[i]=a}return true}
function syncForceSource(r,sourceId,sourceActorId,duration={}){for(const o of r.table.world.objects)for(const f of(o.forces||[]))if(f.sourceId===sourceId&&(!sourceActorId||f.sourceActorId===sourceActorId))f.duration={...f.duration,...clone(duration,{})};for(const a of r.table.encounter.actors)for(const f of(a.forces||[]))if(f.sourceId===sourceId&&(!sourceActorId||f.sourceActorId===sourceActorId))f.duration={...f.duration,...clone(duration,{})}}
function expireForces(r,{round=null,sceneId='',nowMs=now()}={}){const expired=d=>!!d&&((d.expiresAt!=null&&nowMs>d.expiresAt)||(round!=null&&d.expiresRound!=null&&round>d.expiresRound)||(d.kind==='scene'&&d.sceneId&&sceneId&&d.sceneId!==sceneId)),sourceActive=f=>{if(!['concentration','maintenance'].includes(f?.duration?.kind))return true;const a=r.table.encounter.actors.find(x=>x.id===f.sourceActorId);return !!a&&(a.effects||[]).some(e=>e.active!==false&&e.sourceId===f.sourceId)},keep=f=>f&&f.active!==false&&!expired(f.duration)&&sourceActive(f);for(const o of r.table.world.objects)o.forces=(o.forces||[]).filter(keep);for(const a of r.table.encounter.actors)a.forces=(a.forces||[]).filter(keep)}
function applyForceOp(r,op={}){const k=text(op.kind,80),kind=['object','actor'].includes(op.targetKind)?op.targetKind:'object',id=actorId(op.targetId);if(k==='force.upsert')return upsertForce(r,kind,id,op.force,op.destination||op.targetPoint||null);if(k==='force.remove')return removeForce(r,kind,id,actorId(op.forceId||op.id));if(k==='force.source.sync'){syncForceSource(r,text(op.sourceId,180),actorId(op.sourceActorId),op.duration||{});return true}if(k==='force.expire'){expireForces(r,op);return true}return false}


function infoRecord(r={}){r=r&&typeof r==='object'?r:{};return{id:actorId(r.id)||iid('info'),sourceId:text(r.sourceId,180),sourceKind:text(r.sourceKind||'effect',80),sourceActorId:actorId(r.sourceActorId),label:text(r.label||'Information',160),kind:text(r.kind||'insight',80),status:['pending','answered','active','closed'].includes(String(r.status||'pending').toLowerCase())?String(r.status||'pending').toLowerCase():'pending',subject:text(r.subject,500),prompt:text(r.prompt,1000),answer:text(r.answer,4000),precision:num(r.precision,0,10000,0),timeframe:r.timeframe&&typeof r.timeframe==='object'?clone(r.timeframe,{}):null,scope:text(r.scope,240),duration:mutationDuration(r.duration||{}),data:clone(r.data,{}),createdAt:num(r.createdAt||now(),0,Number.MAX_SAFE_INTEGER,now()),updatedAt:num(r.updatedAt||r.createdAt||now(),0,Number.MAX_SAFE_INTEGER,now())}}
function information(x={}){x=x&&typeof x==='object'?x:{};return{records:Array.isArray(x.records)?x.records.slice(0,1000).map(infoRecord):[]}}
const CONTROL_TARGET_KINDS=['actor','object','network','system'],CONTROL_MODES=['exclusive','shared','projected','delegated','remote'];
function controlLease(l={}){l=l&&typeof l==='object'?l:{};return{id:actorId(l.id)||iid('control'),sourceId:text(l.sourceId,180),sourceKind:text(l.sourceKind||'effect',80),sourceActorId:actorId(l.sourceActorId),controllerActorId:actorId(l.controllerActorId||l.sourceActorId),originActorId:actorId(l.originActorId||l.sourceActorId),targetKind:CONTROL_TARGET_KINDS.includes(String(l.targetKind||'object').toLowerCase())?String(l.targetKind||'object').toLowerCase():'object',targetId:actorId(l.targetId),networkId:text(l.networkId,180),anchorObjectId:actorId(l.anchorObjectId),mode:CONTROL_MODES.includes(String(l.mode||'exclusive').toLowerCase())?String(l.mode||'exclusive').toLowerCase():'exclusive',privileges:Array.isArray(l.privileges)?l.privileges.slice(0,20).map(v=>text(v,80)):[],reachMeters:num(l.reachMeters,0,1e9,0),suppressOrigin:!!l.suppressOrigin,allowOriginActions:!!l.allowOriginActions,exclusive:l.exclusive!==false,active:l.active!==false,duration:mutationDuration(l.duration||{}),data:clone(l.data,{}),createdAt:num(l.createdAt||now(),0,Number.MAX_SAFE_INTEGER,now()),updatedAt:num(l.updatedAt||l.createdAt||now(),0,Number.MAX_SAFE_INTEGER,now())}}
function controlState(x={}){x=x&&typeof x==='object'?x:{};return{leases:Array.isArray(x.leases)?x.leases.slice(0,500).map(controlLease):[]}}
function syncControlSource(r,sourceId,sourceActorId,duration={}){let n=0;r.table.control.leases=(r.table.control.leases||[]).map(l=>{if(l.sourceId!==sourceId||l.sourceActorId!==sourceActorId)return l;n++;return controlLease({...l,duration:{...l.duration,...duration},updatedAt:now()})});return n}
function expireControl(r,{round=null,sceneId='',nowMs=now()}={}){const expired=d=>!!d&&((d.expiresAt!=null&&nowMs>d.expiresAt)||(round!=null&&d.expiresRound!=null&&round>d.expiresRound)||(d.kind==='scene'&&d.sceneId&&sceneId&&d.sceneId!==sceneId)),sourceActive=l=>{if(!['maintenance','concentration'].includes(l?.duration?.kind))return true;const a=r.table.encounter.actors.find(x=>x.id===l.sourceActorId);return !!a&&(a.effects||[]).some(e=>e.active!==false&&e.sourceId===l.sourceId)};const before=r.table.control.leases.length;r.table.control.leases=r.table.control.leases.filter(l=>l.active!==false&&!expired(l.duration)&&sourceActive(l));return before-r.table.control.leases.length}
function applyControlOp(r,op={}){const k=text(op.kind,80);if(k==='control.upsert'){const l=controlLease(op.lease),xs=r.table.control.leases,i=xs.findIndex(x=>x.id===l.id);if(i>=0)xs[i]=l;else xs.push(l);r.table.control.leases=xs.slice(-500);return true}if(k==='control.remove'){const id=actorId(op.id),n=r.table.control.leases.length;r.table.control.leases=r.table.control.leases.filter(l=>l.id!==id);return r.table.control.leases.length!==n}if(k==='control.source.sync'){syncControlSource(r,text(op.sourceId,180),actorId(op.sourceActorId),op.duration||{});return true}if(k==='control.expire'){expireControl(r,op);return true}return false}
function originControlAssessment(table,id){const xs=(table.control?.leases||[]).filter(l=>l.active!==false&&l.originActorId===id&&l.suppressOrigin&&!l.allowOriginActions);return xs.length?{ok:false,lease:xs[xs.length-1],code:'ORIGIN_SUPPRESSED'}:{ok:true,code:'ORIGIN_AVAILABLE'}}
function syncInfoSource(r,sourceId,sourceActorId,duration={}){let n=0;r.table.information.records=(r.table.information.records||[]).map(x=>{if(x.sourceId!==sourceId||x.sourceActorId!==sourceActorId)return x;n++;return infoRecord({...x,duration:{...x.duration,...duration},updatedAt:now()})});return n}
function expireInformation(r,{round=null,sceneId='',nowMs=now()}={}){const expired=d=>!!d&&((d.expiresAt!=null&&nowMs>d.expiresAt)||(round!=null&&d.expiresRound!=null&&round>d.expiresRound)||(d.kind==='scene'&&d.sceneId&&sceneId&&d.sceneId!==sceneId));const before=r.table.information.records.length;r.table.information.records=r.table.information.records.filter(x=>x.status!=='closed'&&!expired(x.duration));return before-r.table.information.records.length}
function applyInfoOp(r,op={}){const k=text(op.kind,80);if(k==='info.upsert'){const rec=infoRecord(op.record),xs=r.table.information.records,i=xs.findIndex(x=>x.id===rec.id);if(i>=0)xs[i]=rec;else xs.push(rec);r.table.information.records=xs.slice(-1000);return true}if(k==='info.remove'){const id=actorId(op.id),n=r.table.information.records.length;r.table.information.records=r.table.information.records.filter(x=>x.id!==id);return r.table.information.records.length!==n}if(k==='info.source.sync'){syncInfoSource(r,text(op.sourceId,180),actorId(op.sourceActorId),op.duration||{});return true}if(k==='info.expire'){expireInformation(r,op);return true}return false}
function world(w){w=w&&typeof w==='object'?w:{};return{objects:Array.isArray(w.objects)?w.objects.slice(0,1000).map(worldObject):[]}}
function upsertWorldObject(r,o){const x=worldObject(o),xs=r.table.world.objects||[],i=xs.findIndex(v=>v.id===x.id);if(i>=0)xs[i]=x;else xs.push(x);r.table.world.objects=xs.slice(-1000);return x}
function upsertMutation(r,objectId,m){const obj=r.table.world.objects.find(o=>o.id===objectId);if(!obj)return null;const o=worldObject(obj),x=objectMutation(m);if(!o.mutationBase)o.mutationBase=mutationSnapshot(o);const i=(o.mutations||[]).findIndex(v=>v.id===x.id);if(i>=0)o.mutations[i]=x;else o.mutations=[...(o.mutations||[]),x].slice(-100);rebuildMutations(o);return upsertWorldObject(r,o)}
function removeMutation(r,objectId,mutationId){const obj=r.table.world.objects.find(o=>o.id===objectId);if(!obj)return false;const o=worldObject(obj),n=(o.mutations||[]).length;o.mutations=(o.mutations||[]).filter(m=>m.id!==mutationId);if(o.mutations.length===n)return false;if(!o.mutations.length&&o.mutationBase){for(const k of MUTABLE_OBJECT_KEYS)if(k in o.mutationBase)o[k]=clone(o.mutationBase[k],null);o.mutationBase=null}else rebuildMutations(o);upsertWorldObject(r,o);return true}
function syncWorldSource(r,sourceId,sourceActorId,duration={}){for(const o of(r.table.world.objects||[])){if(o.sourceId===sourceId&&(!sourceActorId||o.sourceActorId===sourceActorId))o.duration={...o.duration,...clone(duration,{})};for(const m of(o.mutations||[]))if(m.sourceId===sourceId&&(!sourceActorId||m.sourceActorId===sourceActorId))m.duration={...m.duration,...clone(duration,{})};for(const f of(o.forces||[]))if(f.sourceId===sourceId&&(!sourceActorId||f.sourceActorId===sourceActorId))f.duration={...f.duration,...clone(duration,{})}};for(const z of(r.table.map.zones||[]))if(z.sourceId===sourceId&&(!sourceActorId||z.sourceActorId===sourceActorId))z.duration={...z.duration,...clone(duration,{})}}
function expireWorld(r,{round=null,sceneId='',nowMs=now()}={}){const expired=d=>!!d&&((d.expiresAt!=null&&nowMs>d.expiresAt)||(round!=null&&d.expiresRound!=null&&round>d.expiresRound)||(d.kind==='scene'&&d.sceneId&&sceneId&&d.sceneId!==sceneId)),sourceActive=x=>{if(!['concentration','maintenance'].includes(x?.duration?.kind))return true;const aid=x.sourceActorId||x.actorId,a=r.table.encounter.actors.find(v=>v.id===aid);return !!a&&(a.effects||[]).some(e=>e.active!==false&&e.sourceId===x.sourceId)},keep=x=>x&&x.active!==false&&!expired(x.duration)&&sourceActive(x);r.table.world.objects=(r.table.world.objects||[]).filter(o=>o.active!==false&&!expired(o.duration)).map(o=>{o=clone(o,{});if(o.state==='disabled'&&Number(o.properties?.disabledUntil||0)>0&&nowMs>Number(o.properties.disabledUntil)){delete o.properties.disabledUntil;o.state=Number(o.health?.current||0)<Number(o.health?.max||0)?'damaged':'intact';if(o.system)o.system.enabled=true}if(o.control?.actorId&&!keep({active:true,actorId:o.control.actorId,sourceActorId:o.control.sourceActorId,sourceId:o.control.sourceId,duration:o.control.duration}))o.control={actorId:'',mode:'',might:0,sourceId:'',sourceActorId:'',duration:{kind:'special',startedRound:null,expiresRound:null,sceneId:'',expiresAt:null}};if(o.system)for(const k of['access','daemons','overrides','marks'])o.system[k]=(o.system[k]||[]).filter(keep);const before=(o.mutations||[]).length;o.mutations=(o.mutations||[]).filter(keep);if(o.mutations.length!==before){if(!o.mutations.length&&o.mutationBase){for(const k of MUTABLE_OBJECT_KEYS)if(k in o.mutationBase)o[k]=clone(o.mutationBase[k],null);o.mutationBase=null}else rebuildMutations(o)}o.forces=(o.forces||[]).filter(keep);return o});r.table.map.zones=(r.table.map.zones||[]).filter(z=>z.active!==false&&!expired(z.duration)&&sourceActive(z))}
function applyWorldOp(r,op={}){const k=text(op.kind,80);if(k==='object.upsert'){upsertWorldObject(r,op.object);return true}if(k==='object.remove'){const n=r.table.world.objects.length;r.table.world.objects=r.table.world.objects.filter(o=>o.id!==actorId(op.id));return r.table.world.objects.length!==n}if(k==='object.mutate')return !!upsertMutation(r,actorId(op.objectId),op.mutation);if(k==='object.mutation.remove')return removeMutation(r,actorId(op.objectId),actorId(op.mutationId));if(k==='zone.upsert'){const z=zone(op.zone),xs=r.table.map.zones||[],i=xs.findIndex(v=>v.id===z.id);if(i>=0)xs[i]=z;else xs.push(z);r.table.map.zones=xs.slice(-500);return true}if(k==='zone.remove'){const n=r.table.map.zones.length;r.table.map.zones=r.table.map.zones.filter(z=>z.id!==actorId(op.id));return r.table.map.zones.length!==n}if(k==='source.sync'){syncWorldSource(r,text(op.sourceId,180),actorId(op.sourceActorId),op.duration||{});return true}if(k==='expire'){expireWorld(r,op);return true}return false}
function map(m,old={}){m=m&&typeof m==='object'?m:{};return{id:actorId(m.id)||actorId(old.id)||iid('map'),assetId:actorId(m.assetId),name:text(m.name||old.name||'Untitled Map',160),columns:num(m.columns,4,300,old.columns||30),rows:num(m.rows,4,300,old.rows||18),gridSize:num(m.gridSize,24,256,old.gridSize||64),distanceUnit:text(m.distanceUnit||old.distanceUnit||'unit',20),unitsPerSquare:num(m.unitsPerSquare,.01,10000,old.unitsPerSquare||1),distanceMetric:['euclidean','grid'].includes(m.distanceMetric)?m.distanceMetric:(old.distanceMetric||'euclidean'),gridVisible:m.gridVisible!==false,snap:m.snap!==false,imageWidth:num(m.imageWidth,1,30000,old.imageWidth||1600),imageHeight:num(m.imageHeight,1,30000,old.imageHeight||900),imageScale:num(m.imageScale,.0001,10000,old.imageScale||1),offsetX:num(m.offsetX,-100000,100000,old.offsetX||0),offsetY:num(m.offsetY,-100000,100000,old.offsetY||0),fogEnabled:!!m.fogEnabled,visionRange:num(m.visionRange,.1,100000,old.visionRange||20),walls:Array.isArray(m.walls)?m.walls.slice(0,500).map(wall):[],zones:Array.isArray(m.zones)?m.zones.slice(0,500).map(zone):[],topography:Array.isArray(m.topography)?m.topography.slice(0,300).map(topo):[],drawings:Array.isArray(m.drawings)?m.drawings.slice(0,500).map(drawing):[],templates:Array.isArray(m.templates)?m.templates.slice(0,300).map(template):[]};}
function proxyState(x){if(!x||typeof x!=='object')return null;const d=x.duration&&typeof x.duration==='object'?x.duration:{},t=x.tether&&typeof x.tether==='object'?x.tether:{},link=x.damageLink&&typeof x.damageLink==='object'?x.damageLink:{};return{active:x.active!==false,proxyType:text(x.proxyType||'proxy',80),sourceId:text(x.sourceId,180),sourceActorId:actorId(x.sourceActorId),controllerActorId:actorId(x.controllerActorId||x.sourceActorId),originObjectId:actorId(x.originObjectId),controlMode:['direct','command','autonomous','mindless','none'].includes(x.controlMode)?x.controlMode:'command',command:text(x.command,500),createdRound:x.createdRound==null?null:num(x.createdRound,0,99999,0),duration:{kind:text(d.kind||'special',40),startedRound:d.startedRound==null?null:num(d.startedRound,0,99999,0),expiresRound:d.expiresRound==null?null:num(d.expiresRound,0,99999,0),sceneId:text(d.sceneId,180),expiresAt:d.expiresAt==null?null:num(d.expiresAt,0,Number.MAX_SAFE_INTEGER,0)},tether:{kind:['none','distance','line-of-sight','los-distance'].includes(t.kind)?t.kind:'none',maxDistanceMeters:num(t.maxDistanceMeters,0,1e9,0),onBreak:['idle','finish-then-idle','expire','return-inanimate','none'].includes(t.onBreak)?t.onBreak:'none'},damageLink:{actorId:actorId(link.actorId),lethalOnDeath:num(link.lethalOnDeath,0,100,0)},data:clone(x.data,{}),createdAt:num(x.createdAt,0,Number.MAX_SAFE_INTEGER,now())}}
function actor(a){a=a&&typeof a==='object'?a:{};const kind=['npc','proxy'].includes(a.kind)?a.kind:'player';return{id:actorId(a.id)||iid('actor'),sourceCharacterId:text(a.sourceCharacterId,180),kind,clientId:kind==='proxy'?'':clientId(a.clientId),name:text(a.name||'Actor',120),secondaryName:text(a.secondaryName,120),rulesetId:text(a.rulesetId,120),footprint:{cols:num(a.footprint?.cols,.25,20,1),rows:num(a.footprint?.rows,.25,20,1)},movement:clone(a.movement,{})||{},initiative:{rating:num(a.initiative?.rating,0,9999,0),enhancedRating:num(a.initiative?.enhancedRating??a.initiative?.rating,0,9999,0),enhancedLevels:num(a.initiative?.enhancedLevels,0,50,0),die:a.initiative?.die==null?null:num(a.initiative.die,1,1000,1),total:a.initiative?.total==null?null:num(a.initiative.total,-99999,99999,0),tieBreakRating:num(a.initiative?.tieBreakRating??a.initiative?.rating,0,9999,0)},health:clone(a.health,{current:0,max:0,damage:[]}),combat:clone(a.combat,{}),resources:clone(a.resources,{}),effects:Array.isArray(a.effects)?clone(a.effects,[]).slice(0,100):[],conditions:Array.isArray(a.conditions)?a.conditions.slice(0,40).map(x=>text(x,80)):[],token:{label:text(a.token?.label||a.name||'Actor',120),color:text(a.token?.color||'#526f7f',32),assetId:actorId(a.token?.assetId||a.token?.assetRef),visionRange:a.token?.visionRange==null?null:num(a.token.visionRange,.1,100000,20)},proxy:proxyState(a.proxy),forces:Array.isArray(a.forces)?a.forces.slice(0,100).map(forceRecord):[],notes:text(a.notes,1000),meta:clone(a.meta,{})};}

function removeActorState(r,id){const e=r.table.encounter,i=e.actors.findIndex(a=>a.id===id);if(i<0)return false;e.actors.splice(i,1);delete r.table.positions[id];delete r.table.elevations[id];delete e.declarations[id];e.delayed=e.delayed.filter(x=>x!==id);e.extraActions=(e.extraActions||[]).filter(x=>x.actorId!==id);if(e.extraActionIndex>e.extraActions.length)e.extraActionIndex=e.extraActions.length;if(e.declarationIndex>=e.actors.length)e.declarationIndex=e.actors.length-1;if(e.resolutionIndex>e.actors.length)e.resolutionIndex=e.actors.length;if(!e.actors.length){e.active=false;e.phase='free';e.declarationIndex=-1;e.resolutionIndex=-1;e.turnIndex=-1;}syncTurnIndex(e);r.table.movement={actorId:'',round:e.round||0,spent:0,mode:'half-run',tokenId:'',path:[]};return true}
function proxyControlAssessment(r,id){const p=r.table.encounter.actors.find(a=>a.id===id&&a.kind==='proxy'),cfg=p?.proxy;if(!p||!cfg)return{ok:false,code:'PROXY_NOT_FOUND'};const c=r.table.encounter.actors.find(a=>a.id===cfg.controllerActorId),pp=r.table.positions[id],cp=r.table.positions[cfg.controllerActorId];if(!c||!pp||!cp)return{ok:false,code:'CONTROLLER_UNAVAILABLE',onBreak:cfg.tether?.onBreak||'none'};const dist=distance2d(r.table.map,cp,pp),tk=cfg.tether?.kind||'none',max=Math.max(0,Number(cfg.tether?.maxDistanceMeters)||0),distanceOk=tk==='none'||tk==='line-of-sight'||!max||dist<=max+1e-7,los=!routeCrossesWall(r.table.map,cp,pp),losOk=!['line-of-sight','los-distance'].includes(tk)||los;return{ok:distanceOk&&losOk,code:distanceOk&&losOk?'LINK_ACTIVE':'LINK_BROKEN',distanceMeters:dist,lineOfSight:los,maxDistanceMeters:max,onBreak:cfg.tether?.onBreak||'none'}}
function syncProxySource(r,sourceId,sourceActorId,duration={}){for(const a of r.table.encounter.actors)if(a.kind==='proxy'&&a.proxy?.sourceId===sourceId&&(!sourceActorId||a.proxy.sourceActorId===sourceActorId))a.proxy.duration={...a.proxy.duration,...clone(duration,{})}}
function expireProxyActors(r,{round=null,sceneId='',nowMs=now()}={}){const expired=d=>!!d&&((d.expiresAt!=null&&nowMs>d.expiresAt)||(round!=null&&d.expiresRound!=null&&round>d.expiresRound)||(d.kind==='scene'&&d.sceneId&&sceneId&&d.sceneId!==sceneId)),ids=[];for(const a of [...r.table.encounter.actors]){if(a.kind!=='proxy'||!a.proxy)continue;const pr=a.proxy,source=r.table.encounter.actors.find(x=>x.id===pr.sourceActorId),sourceActive=!['maintenance','concentration'].includes(pr.duration?.kind)||!!source&&(source.effects||[]).some(e=>e.active!==false&&e.sourceId===pr.sourceId);let gone=pr.active===false||expired(pr.duration)||!sourceActive;if(!gone&&pr.tether?.onBreak==='expire')gone=!proxyControlAssessment(r,a.id).ok;if(gone){ids.push(a.id);removeActorState(r,a.id)}}return ids}
function upsertProxy(r,raw,position=null){const a=actor({...raw,kind:'proxy',clientId:''}),xs=r.table.encounter.actors,i=xs.findIndex(x=>x.id===a.id);if(i>=0)xs[i]=a;else if(xs.length<200)xs.push(a);else return null;if(position)r.table.positions[a.id]=point(position);else if(!r.table.positions[a.id])r.table.positions[a.id]={x:r.table.map.gridSize*3,y:r.table.map.gridSize*3};if(r.table.elevations[a.id]==null)r.table.elevations[a.id]=0;return a}
function applyActorOp(r,op={}){const k=text(op.kind,80);if(k==='proxy.upsert')return !!upsertProxy(r,op.actor,op.position);if(k==='proxy.remove')return removeActorState(r,actorId(op.id));if(k==='proxy.source.sync'){syncProxySource(r,text(op.sourceId,180),actorId(op.sourceActorId),op.duration||{});return true}if(k==='proxy.expire'){expireProxyActors(r,op);return true}return false}
function safeActorPatch(p={}){p=p&&typeof p==='object'?p:{};const out={};if(p.health&&typeof p.health==='object')out.health=clone(p.health,{});if(p.resources&&typeof p.resources==='object')out.resources=clone(p.resources,{});if(p.conditions&&Array.isArray(p.conditions))out.conditions=p.conditions.slice(0,40).map(x=>text(x,80));if(p.combat&&typeof p.combat==='object')out.combat=clone(p.combat,{});if(p.effects&&Array.isArray(p.effects))out.effects=clone(p.effects,[]).slice(0,100);if(p.notes!==undefined)out.notes=text(p.notes,1000);return out;}
function declaration(d={},id='',round=1){d=d&&typeof d==='object'?d:{};const a=d.action&&typeof d.action==='object'?d.action:{},m=d.movement&&typeof d.movement==='object'?d.movement:{},status=['draft','locked','delayed','resolving','resolved','fizzled','aborted-defense'].includes(d.status)?d.status:(d.locked?'locked':'draft');return{actorId:actorId(d.actorId||id),round:num(d.round,1,99999,round),locked:!!d.locked,status,action:{kind:(()=>{const k=text(a.kind||'other',80);return /^[A-Za-z0-9][A-Za-z0-9_-]{0,79}$/.test(k)?k:'other'})(),label:text(a.label,160),intent:text(a.intent,1000),targetActorId:actorId(a.targetActorId),targetFeatureId:actorId(a.targetFeatureId),maneuverId:text(a.maneuverId,120),refId:text(a.refId||'',160),payload:clone(a.payload,{})},movement:{kind:['none','approach','chase','flee','take-cover','jump','general'].includes(m.kind)?m.kind:'none',intent:text(m.intent,1000),targetActorId:actorId(m.targetActorId),targetFeatureId:actorId(m.targetFeatureId),targetPoint:m.targetPoint?point(m.targetPoint):null,originPoint:m.originPoint?point(m.originPoint):null,direction:m.direction?{x:num(m.direction.x,-1,1,0),y:num(m.direction.y,-1,1,0)}:null,expectedMode:text(m.expectedMode,40)},totalActions:num(d.totalActions,1,30,1),notes:text(d.notes,1000),declaredAt:num(d.declaredAt,0,Number.MAX_SAFE_INTEGER,0),resolvedAt:num(d.resolvedAt,0,Number.MAX_SAFE_INTEGER,0),resolution:clone(d.resolution,{}),abortRequest:d.abortRequest&&typeof d.abortRequest==='object'?clone(d.abortRequest):null}}
function extraSlot(x={}){return{id:text(x.id||iid('extra'),220),actorId:actorId(x.actorId),ordinal:num(x.ordinal,1,100,1),pass:num(x.pass||x.ordinal,1,100,1),actionKind:text(x.actionKind||'physical',40),label:text(x.label||'Extra action',160),sourceLabels:Array.isArray(x.sourceLabels)?x.sourceLabels.slice(0,20).map(v=>text(v,160)):[]}}
function syncTurnIndex(e){if(!e.active||e.phase==='free')e.turnIndex=-1;else if(e.phase==='declaration')e.turnIndex=e.declarationIndex;else if(e.interrupt?.actorId)e.turnIndex=e.actors.findIndex(a=>a.id===e.interrupt.actorId);else if(e.resolutionIndex>=0&&e.resolutionIndex<e.actors.length)e.turnIndex=e.resolutionIndex;else if(e.extraActionIndex>=0&&e.extraActionIndex<(e.extraActions||[]).length)e.turnIndex=e.actors.findIndex(a=>a.id===e.extraActions[e.extraActionIndex]?.actorId);else e.turnIndex=-1;return e.turnIndex}
function encounter(e={}){let xs=Array.isArray(e.actors)?e.actors.slice(0,200).map(actor):[],active=!!e.active,legacy=!e.phase,phase=active?(legacy?'declaration':(['declaration','resolution'].includes(e.phase)?e.phase:'declaration')):'free',decls={};if(e.declarations&&typeof e.declarations==='object')for(const a of xs)if(e.declarations[a.id])decls[a.id]=declaration(e.declarations[a.id],a.id,e.round||1);const extras=Array.isArray(e.extraActions)?e.extraActions.slice(0,1000).map(extraSlot).filter(x=>xs.some(a=>a.id===x.actorId)):[];const out={active,sceneId:text(e.sceneId||'',180),round:num(e.round,1,99999,1),phase,declarationIndex:phase==='declaration'?num(legacy?xs.length-1:(e.declarationIndex??xs.length-1),-1,xs.length?xs.length-1:-1,xs.length-1):-1,resolutionIndex:phase==='resolution'?num(e.resolutionIndex??e.turnIndex??0,0,xs.length,0):-1,extraActions:extras,extraActionIndex:num(e.extraActionIndex,0,extras.length,0),turnIndex:-1,actors:xs,declarations:decls,delayed:Array.isArray(e.delayed)?e.delayed.map(actorId).filter(id=>xs.some(a=>a.id===id)).slice(0,200):[],interrupt:e.interrupt&&xs.some(a=>a.id===actorId(e.interrupt.actorId))?{actorId:actorId(e.interrupt.actorId),type:e.interrupt.type==='delay'?'delay':'interrupt',returnIndex:num(e.interrupt.returnIndex,0,xs.length,0)}:null,updatedAt:num(e.updatedAt,0,Number.MAX_SAFE_INTEGER,now())};syncTurnIndex(out);return out}
function cleanFeature(kind,x){return kind==='wall'?wall(x):kind==='zone'?zone(x):kind==='topography'?topo(x):kind==='drawing'?drawing(x):kind==='template'?template(x):null}
function blankTable(){return{map:map({id:'map:default',name:'Untitled Map',distanceUnit:'unit',unitsPerSquare:1}),world:world(),information:information(),control:controlState(),positions:{},elevations:{},supports:{},mapPositionSets:{},movement:{actorId:'',round:0,spent:0,mode:'half-run',tokenId:'',path:[]},encounter:encounter(),reveal:{active:false,assetId:'',name:'',serial:0,updatedAt:now()},log:[],updatedAt:now()}}
function roomState(room,forClient=''){return{type:'room_state',protocol:PROTOCOL,version:VERSION,code:room.code,ownerId:room.ownerId,rulesetId:room.rulesetId,rulesFingerprint:room.rulesFingerprint,profileName:room.profileName,members:[...room.members.values()].map(m=>({clientId:m.clientId,role:m.role,name:m.name,connected:!!m.conn,actorId:m.actorId})),sessionTools:clone(room.sessionTools||blankSessionTools()),table:clone(room.table),revision:room.revision,serverTime:now(),you:forClient};}
function touch(room){room.updatedAt=now();room.revision++;room.table.updatedAt=room.updatedAt;}
function sendErr(conn,message,code='ERROR',extra={}){conn.sendJSON({type:'error',protocol:PROTOCOL,code,message,...extra})}
function broadcast(room){for(const m of room.members.values())if(m.conn)m.conn.sendJSON(roomState(room,m.clientId));}
function assertGm(room,cid,conn){if(room.ownerId!==cid){sendErr(conn,'GM authority required.','GM_AUTHORITY_REQUIRED');return false}return true}
function memberCanMove(room,cid,id){if(room.ownerId===cid)return true;const m=room.members.get(cid),a=room.table.encounter.actors.find(x=>x.id===id);if(!m||!a)return false;if(a.clientId===cid||m.actorId===id)return originControlAssessment(room.table,id).ok;if(a.kind==='proxy'&&a.proxy?.controllerActorId===m.actorId)return proxyControlAssessment(room,id).ok;return false;}
function inBounds(room,p){const m=room.table.map,w=m.columns*m.gridSize,h=m.rows*m.gridSize;return p.x>=0&&p.y>=0&&p.x<=w&&p.y<=h}
function segmentIntersects(a,b,c,d){const o=(p,q,r)=>(q.x-p.x)*(r.y-p.y)-(q.y-p.y)*(r.x-p.x);const x1=o(a,b,c),x2=o(a,b,d),x3=o(c,d,a),x4=o(c,d,b);return ((x1>0&&x2<0)||(x1<0&&x2>0))&&((x3>0&&x4<0)||(x3<0&&x4>0));}
function pointInRect(p,z){return p.x>=Math.min(z.x1,z.x2)&&p.x<=Math.max(z.x1,z.x2)&&p.y>=Math.min(z.y1,z.y2)&&p.y<=Math.max(z.y1,z.y2)}
function pointInPoly(p,pts){let inside=false;for(let i=0,j=pts.length-1;i<pts.length;j=i++){const a=pts[i],b=pts[j];if(((a.y>p.y)!==(b.y>p.y))&&(p.x<(b.x-a.x)*(p.y-a.y)/(b.y-a.y||1e-9)+a.x))inside=!inside;}return inside}
function inFeature(p,z){return z.shape==='poly'?pointInPoly(p,z.points||[]):pointInRect(p,z)}
function routeCrossesWall(m,a,b){return m.walls.some(w=>segmentIntersects(a,b,{x:w.x1,y:w.y1},{x:w.x2,y:w.y2}))}
function topologyGate(m,a,b){for(const z of m.topography){const entered=!inFeature(a,z)&&inFeature(b,z);if(!entered)continue;if(z.blockMovement)return{kind:'blocked',feature:z};if(z.checkRequired)return{kind:'check',feature:z,check:z.check};}return null}
function distance2d(m,a,b){const upp=(m.unitsPerSquare||1)/(m.gridSize||64),dx=(b.x-a.x)*upp,dy=(b.y-a.y)*upp;return m.distanceMetric==='grid'?Math.max(Math.abs(dx),Math.abs(dy)):Math.hypot(dx,dy)}
function schedulerEffects(a,round){round=Number(round);return(a?.effects||[]).filter(e=>e&&e.active!==false&&e.data?.scheduler&&(!Number.isFinite(round)||((e.startedRound==null||Number(e.startedRound)<=round)&&(e.expiresRound==null||Number(e.expiresRound)>=round))))}
function schedulerHints(a,round){const out={extraActions:0,initiativeModifier:0,suspended:false,alternate:[],sourceLabels:[]};for(const e of schedulerEffects(a,round)){const h=e.data.scheduler||{};out.extraActions+=Math.max(0,num(h.extraActions,0,50,0));out.initiativeModifier+=num(h.initiativeModifier,-10000,10000,0);out.suspended=out.suspended||!!h.suspended;if(h.everyOtherTurnBelow!=null)out.alternate.push({threshold:num(h.everyOtherTurnBelow,-10000,10000,1),anchorRound:Number.isFinite(Number(h.anchorRound))?Number(h.anchorRound):(Number.isFinite(Number(e.startedRound))?Number(e.startedRound):Number(round)||1)});out.sourceLabels.push(text(e.label||e.sourceId||'Scheduled effect',160))}out.extraActions=Math.min(50,out.extraActions);return out}
function effectiveInitiative(a,round){const base=a?.initiative?.total==null?-1e9:Number(a.initiative.total)||0;return base+schedulerHints(a,round).initiativeModifier}
function actorTurnAvailable(a,round){if(!a)return false;const h=schedulerHints(a,round);if(h.suspended)return false;const eff=effectiveInitiative(a,round);for(const x of h.alternate)if(eff<x.threshold&&Math.abs((Number(round)||1)-x.anchorRound)%2===1)return false;return true}
function buildExtraActions(e){const max=Math.max(0,...e.actors.map(a=>!a.health?.dead&&actorTurnAvailable(a,e.round)?schedulerHints(a,e.round).extraActions:0)),out=[];for(let pass=1;pass<=max;pass++)for(const a of e.actors){if(a.health?.dead||!actorTurnAvailable(a,e.round))continue;const h=schedulerHints(a,e.round);if(h.extraActions>=pass)out.push(extraSlot({id:`extra:${e.round}:${a.id}:${pass}`,actorId:a.id,ordinal:pass,pass,actionKind:'physical',label:`Extra physical action ${pass}/${h.extraActions}`,sourceLabels:h.sourceLabels}))}return out}
function refreshExtraActions(r,force=false){const e=r.table.encounter;if(!e.active){e.extraActions=[];e.extraActionIndex=0;return}if(e.phase==='resolution'&&e.resolutionIndex>=e.actors.length&&e.extraActionIndex>0&&!force)return;e.extraActions=buildExtraActions(e);e.extraActionIndex=0;syncTurnIndex(e)}
function currentSlot(r){const e=r.table.encounter;if(!e.active||e.phase!=='resolution')return null;if(e.interrupt?.actorId)return{kind:'interrupt',actorId:e.interrupt.actorId};if(e.resolutionIndex>=0&&e.resolutionIndex<e.actors.length)return{kind:'primary',actorId:e.actors[e.resolutionIndex].id};if(e.extraActionIndex>=0&&e.extraActionIndex<(e.extraActions||[]).length)return{kind:'extra',...e.extraActions[e.extraActionIndex]};return null}
function currentActor(r){const e=r.table.encounter;if(!e.active)return null;if(e.phase==='declaration')return e.declarationIndex>=0?e.actors[e.declarationIndex]||null:null;if(e.phase==='resolution'){const slot=currentSlot(r);return slot?e.actors.find(a=>a.id===slot.actorId)||null:null}return null}
function featureById(m,id){if(!id)return null;for(const k of ['walls','zones','topography','drawings','templates']){const x=(m[k]||[]).find(v=>v.id===id);if(x)return x}return null}
function sortActors(e,round=e.round||1){e.actors.sort((a,b)=>effectiveInitiative(b,round)-effectiveInitiative(a,round)||(b.initiative.tieBreakRating??b.initiative.rating??0)-(a.initiative.tieBreakRating??a.initiative.rating??0)||a.name.localeCompare(b.name));return e}
function allSuspended(e){const live=e.actors.filter(a=>!a.health?.dead);return live.length>0&&live.every(a=>schedulerHints(a,e.round).suspended)}
function normalizeDeclaration(r){const e=r.table.encounter;if(!e.active||e.phase!=='declaration')return currentActor(r);while(e.declarationIndex>=0&&!actorTurnAvailable(e.actors[e.declarationIndex],e.round))e.declarationIndex--;syncTurnIndex(e);if(e.declarationIndex<0)enterResolution(r);return currentActor(r)}
function startRound(r,round=1){const e=r.table.encounter,wasActive=!!e.active;e.active=e.actors.length>0;if(e.active&&round===1&&!wasActive)e.sceneId=iid('scene');e.round=Math.max(1,round);expireWorld(r,{round:e.round,sceneId:e.sceneId});expireForces(r,{round:e.round,sceneId:e.sceneId});expireInformation(r,{round:e.round,sceneId:e.sceneId});expireControl(r,{round:e.round,sceneId:e.sceneId});expireProxyActors(r,{round:e.round,sceneId:e.sceneId});if(e.active)sortActors(e,e.round);e.phase=e.active?'declaration':'free';e.declarationIndex=e.active?e.actors.length-1:-1;e.resolutionIndex=-1;e.extraActions=[];e.extraActionIndex=0;e.declarations={};e.delayed=[];e.interrupt=null;syncTurnIndex(e);r.table.movement={actorId:'',round:e.round,spent:0,mode:'half-run',tokenId:'',path:[]};e.updatedAt=now();if(e.active)normalizeDeclaration(r);return currentActor(r)}
function normalizeResolution(r){const e=r.table.encounter;if(!e.active||e.phase!=='resolution'||e.interrupt)return currentActor(r);while(e.resolutionIndex<e.actors.length){const a=e.actors[e.resolutionIndex],id=a.id,d=e.declarations[id];if(!actorTurnAvailable(a,e.round)){if(d?.locked&&!['resolved','fizzled','aborted-defense'].includes(d.status)){d.status='fizzled';d.resolvedAt=now();d.resolution={...(d.resolution||{}),outcome:'fizzled',schedulerSkipped:true}}e.resolutionIndex++;continue}if(!d?.locked||['resolved','fizzled','aborted-defense'].includes(d.status)){e.resolutionIndex++;continue}if(d.action?.kind==='delay'&&d.status!=='delayed'){d.status='delayed';if(!e.delayed.includes(id))e.delayed.push(id);e.resolutionIndex++;continue}break}while(e.resolutionIndex>=e.actors.length&&e.extraActionIndex<(e.extraActions||[]).length){const x=e.extraActions[e.extraActionIndex],a=e.actors.find(v=>v.id===x.actorId);if(!a||a.health?.dead||!actorTurnAvailable(a,e.round)){e.extraActionIndex++;continue}break}syncTurnIndex(e);if(e.resolutionIndex>=e.actors.length&&e.extraActionIndex>=(e.extraActions||[]).length&&!e.delayed.length){if(allSuspended(e))return null;startRound(r,e.round+1)}return currentActor(r)}
function enterResolution(r){const e=r.table.encounter;e.phase='resolution';e.declarationIndex=-1;e.resolutionIndex=0;e.interrupt=null;refreshExtraActions(r,true);syncTurnIndex(e);r.table.movement={actorId:'',round:e.round,spent:0,mode:'half-run',tokenId:'',path:[]};return normalizeResolution(r)}
function lockDeclarationServer(r,id,draft){const e=r.table.encounter,d=declaration({...draft,actorId:id,round:e.round,locked:true,status:'locked',declaredAt:now()},id,e.round),pos=r.table.positions[id];if(d.movement.kind!=='none'){if(!d.movement.originPoint&&pos)d.movement.originPoint=point(pos);if(!d.movement.targetPoint&&d.movement.targetActorId&&r.table.positions[d.movement.targetActorId])d.movement.targetPoint=point(r.table.positions[d.movement.targetActorId]);if(d.movement.originPoint&&d.movement.targetPoint){const dx=d.movement.targetPoint.x-d.movement.originPoint.x,dy=d.movement.targetPoint.y-d.movement.originPoint.y,l=Math.hypot(dx,dy);if(l>1e-7)d.movement.direction={x:dx/l,y:dy/l}}}e.declarations[id]=d;if(e.declarationIndex>0){e.declarationIndex--;normalizeDeclaration(r)}else enterResolution(r);syncTurnIndex(e);r.table.movement={actorId:'',round:e.round,spent:0,mode:'half-run',tokenId:'',path:[]};e.updatedAt=now();return d}
function finishResolutionServer(r,outcome='resolved',details={}){const e=r.table.encounter,slot=currentSlot(r),a=currentActor(r);if(!a)return false;const d=e.declarations[a.id],resolved=outcome==='fizzled'?'fizzled':'resolved';if(slot?.kind==='extra'){if(d){const extras=Array.isArray(d.resolution?.extraActions)?d.resolution.extraActions:[];d.resolution={...(d.resolution||{}),extraActions:[...extras,{slotId:slot.id,ordinal:slot.ordinal,outcome:resolved,at:now(),...clone(details,{})}]}}e.extraActionIndex++}else{if(d){d.status=resolved;d.resolvedAt=now();d.resolution={...(d.resolution||{}),...clone(details,{}),outcome:d.status}}if(e.interrupt?.actorId===a.id){e.delayed=e.delayed.filter(id=>id!==a.id);e.interrupt=null}else e.resolutionIndex++}normalizeResolution(r);syncTurnIndex(e);r.table.movement={actorId:'',round:e.round,spent:0,mode:'half-run',tokenId:'',path:[]};return true}
function movementIntent(r,id,from,to,gmOverride=false){if(gmOverride||!r.table.encounter.active)return{ok:true,code:gmOverride?'ST_OVERRIDE':'FREE_PLAY'};const d=r.table.encounter.declarations?.[id];if(!d?.locked)return{ok:false,code:'NO_LOCKED_DECLARATION'};const m=d.movement||{};if(m.kind==='none')return{ok:false,code:'UNDECLARED_MOVEMENT'};const mp=r.table.map,tol=Math.max(.01,(mp.unitsPerSquare||1)*.35),ta=m.targetActorId?r.table.encounter.actors.find(a=>a.id===m.targetActorId):null,tp=ta?r.table.positions[ta.id]:null,before=tp?distance2d(mp,from,tp):null,after=tp?distance2d(mp,to,tp):null;if(['approach','chase'].includes(m.kind)&&tp)return{ok:after<=before+tol,code:after<=before+tol?'INTENT_OK':'INTENT_DIVERGENCE'};if(m.kind==='flee'&&tp)return{ok:after+tol>=before,code:after+tol>=before?'INTENT_OK':'INTENT_DIVERGENCE'};const target=m.targetPoint,origin=m.originPoint||from;if(target){const ox=target.x-origin.x,oy=target.y-origin.y,ol=Math.hypot(ox,oy),cx=to.x-from.x,cy=to.y-from.y,cl=Math.hypot(cx,cy);if(cl<=1e-7)return{ok:true,code:'NO_MOVEMENT'};const near=Math.hypot(to.x-target.x,to.y-target.y)<=(mp.gridSize||64)*1.5;if(ol>1e-7){const cos=(ox*cx+oy*cy)/(ol*cl);return{ok:near||cos>=.5,code:near?'DECLARED_AREA':cos>=.5?'CONTINUE_DIRECTION':'INTENT_DIVERGENCE',targetFeatureMissing:!!m.targetFeatureId&&!featureById(mp,m.targetFeatureId)}}return{ok:near,code:near?'DECLARED_AREA':'INTENT_DIVERGENCE'}}return{ok:true,code:'SEMANTIC_INTENT'}}
function movementMode(a,id){const modes=a?.movement?.modes||{};return modes[id]||modes['half-run']||modes.halfRun||Object.values(modes)[0]||null}
function addLog(room,kind,message,who=''){room.table.log=room.table.log||[];room.table.log.push({id:iid('log'),kind:text(kind,60),message:text(message,1000),who:text(who,120),round:room.table.encounter.round||0,at:now()});room.table.log=room.table.log.slice(-MAX_LOG);}
function createRoom(conn,msg,cid){const code=makeCode(),rulesFingerprint=text(msg.rulesFingerprint,1000),rulesetId=text(msg.rulesetId,120);const t=blankTable();if(msg.table?.map)t.map=map(msg.table.map,t.map);if(msg.table?.world)t.world=world(msg.table.world);if(msg.table?.information)t.information=information(msg.table.information);if(msg.table?.control)t.control=controlState(msg.table.control);const r={code,ownerId:cid,rulesFingerprint,rulesetId,profileName:text(msg.profileName||rulesetId||'Storyteller d10',120),members:new Map(),assets:new Map(),sessionTools:blankSessionTools(),table:t,revision:1,createdAt:now(),updatedAt:now(),emptyAt:null};rooms.set(code,r);const m={clientId:cid,role:'gm',name:text(msg.name||'Storyteller',120),actorId:'',conn};r.members.set(cid,m);conn.roomCode=code;conn.clientId=cid;addLog(r,'SESSION','Room created.',m.name);conn.sendJSON({type:'room_created',protocol:PROTOCOL,code,ownerId:cid});broadcast(r);}
function joinRoom(conn,msg,cid){const code=roomCode(msg.code),r=rooms.get(code);if(!r)return sendErr(conn,'Room not found.','ROOM_NOT_FOUND');if(r.rulesFingerprint&&text(msg.rulesFingerprint,1000)!==r.rulesFingerprint)return sendErr(conn,'Rules profile mismatch.','RULES_MISMATCH',{expected:r.rulesFingerprint,received:text(msg.rulesFingerprint,1000)});let m=r.members.get(cid);if(!m)m={clientId:cid,role:'player',name:text(msg.name||'Player',120),actorId:'',conn};m.conn=conn;m.name=text(msg.name||m.name||'Player',120);r.members.set(cid,m);conn.roomCode=code;conn.clientId=cid;r.emptyAt=null;addLog(r,'SESSION',`${m.name} joined.`,m.name);conn.sendJSON({type:'room_joined',protocol:PROTOCOL,code,ownerId:r.ownerId});for(const a of r.assets.values())conn.sendJSON({type:'asset',protocol:PROTOCOL,asset:a});broadcast(r);}
function detach(conn){const r=rooms.get(conn.roomCode);if(!r)return;const m=r.members.get(conn.clientId);if(m&&m.conn===conn)m.conn=null;addLog(r,'SESSION',`${m?.name||conn.clientId} disconnected.`,m?.name||'');if(![...r.members.values()].some(x=>x.conn))r.emptyAt=now();touch(r);broadcast(r);}
function handle(conn,msg,cid){const r=rooms.get(conn.roomCode);if(!r)return sendErr(conn,'Join a room first.','NOT_IN_ROOM');if(conn.clientId!==cid)return sendErr(conn,'Client id changed during session.','CLIENT_ID_MISMATCH');const m=r.members.get(cid);if(!m)return sendErr(conn,'Member missing.','MEMBER_MISSING');switch(msg.type){
 case 'presence_update':{m.name=text(msg.name||m.name,120);if(msg.actor){let a=actor({...msg.actor,kind:'player',clientId:cid});const existing=r.table.encounter.actors.findIndex(x=>x.id===a.id);if(existing>=0)r.table.encounter.actors[existing]=a;else if(r.table.encounter.actors.length<200)r.table.encounter.actors.push(a);m.actorId=a.id;if(!r.table.positions[a.id])r.table.positions[a.id]={x:r.table.map.gridSize*1.5,y:r.table.map.gridSize*1.5};}touch(r);broadcast(r);break;}
 case 'map_set':{if(!assertGm(r,cid,conn))break;const oldId=r.table.map.id;r.table.mapPositionSets[oldId]={positions:clone(r.table.positions,{}),elevations:clone(r.table.elevations,{})};r.table.map=map(msg.map,r.table.map);const saved=r.table.mapPositionSets[r.table.map.id];r.table.positions=clone(saved?.positions,{})||{};r.table.elevations=clone(saved?.elevations,{})||{};for(let i=0;i<r.table.encounter.actors.length;i++){const a=r.table.encounter.actors[i];if(!r.table.positions[a.id]){const g=r.table.map.gridSize||64;r.table.positions[a.id]={x:((i%Math.max(1,r.table.map.columns-2))+1.5)*g,y:(Math.floor(i/Math.max(1,r.table.map.columns-2))+1.5)*g};}if(r.table.elevations[a.id]==null)r.table.elevations[a.id]=0;}touch(r);addLog(r,'MAP',`Map set to ${r.table.map.name}.`,m.name);broadcast(r);break;}
 case 'feature_add':{if(!assertGm(r,cid,conn))break;const k=text(msg.kind,30),f=cleanFeature(k,{...msg.feature,ownerId:cid});if(!f)return sendErr(conn,'Unsupported feature.','BAD_FEATURE');const key=k==='wall'?'walls':k==='zone'?'zones':k==='topography'?'topography':k==='drawing'?'drawings':'templates';r.table.map[key].push(f);touch(r);broadcast(r);break;}
 case 'feature_remove':{if(!assertGm(r,cid,conn))break;for(const key of ['walls','zones','topography','drawings','templates'])r.table.map[key]=r.table.map[key].filter(x=>x.id!==msg.id);touch(r);broadcast(r);break;}
 case 'feature_clear':{if(!assertGm(r,cid,conn))break;const key=msg.kind==='wall'?'walls':msg.kind==='zone'?'zones':msg.kind==='topography'?'topography':msg.kind==='drawing'?'drawings':msg.kind==='template'?'templates':null;if(key)r.table.map[key]=[];else for(const k of ['walls','zones','topography','drawings','templates'])r.table.map[k]=[];touch(r);broadcast(r);break;}
 case 'actor_ops':{if(!assertGm(r,cid,conn))break;const ops=Array.isArray(msg.ops)?msg.ops.slice(0,100):[];for(const op of ops)if(!applyActorOp(r,op))return sendErr(conn,`Unsupported actor operation: ${text(op?.kind,80)}`,'BAD_ACTOR_OPERATION');touch(r);addLog(r,'ACTOR',text(msg.reason||`Applied ${ops.length} actor operation${ops.length===1?'':'s'}.`,220),m.name);broadcast(r);break;}
 case 'world_ops':{if(!assertGm(r,cid,conn))break;const ops=Array.isArray(msg.ops)?msg.ops.slice(0,100):[];for(const op of ops)if(!applyWorldOp(r,op))return sendErr(conn,`Unsupported world operation: ${text(op?.kind,80)}`,'BAD_WORLD_OPERATION');touch(r);addLog(r,'WORLD',text(msg.reason||`Applied ${ops.length} world operation${ops.length===1?'':'s'}.`,220),m.name);broadcast(r);break;}
 case 'force_ops':{if(!assertGm(r,cid,conn))break;const ops=Array.isArray(msg.ops)?msg.ops.slice(0,100):[];for(const op of ops)if(!applyForceOp(r,op))return sendErr(conn,`Unsupported force operation: ${text(op?.kind,80)}`,'BAD_FORCE_OPERATION');touch(r);addLog(r,'FORCE',text(msg.reason||`Applied ${ops.length} force operation${ops.length===1?'':'s'}.`,220),m.name);broadcast(r);break;}
 case 'info_ops':{if(!assertGm(r,cid,conn))break;const ops=Array.isArray(msg.ops)?msg.ops.slice(0,100):[];for(const op of ops)if(!applyInfoOp(r,op))return sendErr(conn,`Unsupported information operation: ${text(op?.kind,80)}`,'BAD_INFORMATION_OPERATION');touch(r);addLog(r,'INFO',text(msg.reason||`Applied ${ops.length} information operation${ops.length===1?'':'s'}.`,220),m.name);broadcast(r);break;}
 case 'control_ops':{if(!assertGm(r,cid,conn))break;const ops=Array.isArray(msg.ops)?msg.ops.slice(0,100):[];for(const op of ops)if(!applyControlOp(r,op))return sendErr(conn,`Unsupported control operation: ${text(op?.kind,80)}`,'BAD_CONTROL_OPERATION');touch(r);addLog(r,'CONTROL',text(msg.reason||`Applied ${ops.length} control operation${ops.length===1?'':'s'}.`,220),m.name);broadcast(r);break;}
 case 'token_move':{const id=actorId(msg.actorId);if(!memberCanMove(r,cid,id))return sendErr(conn,'You cannot move that actor.','TOKEN_AUTHORITY_REQUIRED');const a=r.table.encounter.actors.find(x=>x.id===id);if(!a)return sendErr(conn,'Actor not found.','ACTOR_NOT_FOUND');if(a.health?.dead&&!(cid===r.ownerId&&!!msg.gmOverride))return sendErr(conn,'That actor can no longer act.','ACTOR_CANNOT_ACT');const from=point(r.table.positions[id]||msg.from||{}),to=point(msg.to),gmOverride=cid===r.ownerId&&!!msg.gmOverride;if(!inBounds(r,to))return sendErr(conn,'Destination is outside the map.','OUT_OF_BOUNDS');if(r.table.encounter.active&&(r.table.encounter.phase!=='resolution'||currentActor(r)?.id!==id)&&!gmOverride)return sendErr(conn,r.table.encounter.phase==='declaration'?'Movement resolves after declarations are locked.':'It is not that actor’s resolution.','OUT_OF_TURN');const intent=movementIntent(r,id,from,to,gmOverride);if(!intent.ok)return sendErr(conn,'Movement leaves the actor’s locked declaration.','INTENT_DIVERGENCE',{intentCode:intent.code});if(routeCrossesWall(r.table.map,from,to)&&!gmOverride)return sendErr(conn,'Movement crosses a blocking wall.','VTT_BLOCKED');const gate=topologyGate(r.table.map,from,to);if(gate?.kind==='blocked'&&!gmOverride)return sendErr(conn,'Movement is blocked by topography.','VTT_BLOCKED',{featureId:gate.feature.id});if(gate?.kind==='check'&&!msg.topographyApproved&&!gmOverride)return sendErr(conn,'A ruleset traversal check is required.','VTT_CHECK_REQUIRED',{featureId:gate.feature.id,check:gate.check,from,to,actorId:id});const modeId=text(msg.mode||r.table.movement.mode||'half-run',40),mode=movementMode(a,modeId),step=distance2d(r.table.map,from,to),same=r.table.movement.actorId===id&&r.table.movement.round===r.table.encounter.round,spent=r.table.encounter.active?(same?num(r.table.movement.spent,0,1e9,0):0):0;if(r.table.encounter.active&&mode&&Number.isFinite(Number(mode.distance))&&spent+step>Number(mode.distance)+1e-7&&!gmOverride)return sendErr(conn,'Movement exceeds the actor movement budget.','MOVE_BUDGET',{spent,step,limit:Number(mode.distance),mode:modeId});r.table.positions[id]=to;r.table.movement={actorId:id,round:r.table.encounter.round||0,spent:r.table.encounter.active?spent+step:0,mode:modeId,tokenId:id,path:same&&Array.isArray(r.table.movement.path)?[...r.table.movement.path,to].slice(-100):[from,to]};if(a.kind==='proxy'&&a.proxy){const link=proxyControlAssessment(r,id);if(!link.ok&&link.onBreak==='expire')removeActorState(r,id);}touch(r);broadcast(r);break;}
 case 'elevation_set':{const id=actorId(msg.actorId);if(!memberCanMove(r,cid,id))return sendErr(conn,'You cannot edit that actor.','TOKEN_AUTHORITY_REQUIRED');r.table.elevations[id]=num(msg.elevation,-10000,10000,0);touch(r);broadcast(r);break;}
 case 'npc_upsert':{if(!assertGm(r,cid,conn))break;const a=actor({...msg.actor,kind:'npc',clientId:''});const i=r.table.encounter.actors.findIndex(x=>x.id===a.id);if(i>=0)r.table.encounter.actors[i]=a;else if(r.table.encounter.actors.length<200)r.table.encounter.actors.push(a);if(!r.table.positions[a.id])r.table.positions[a.id]={x:r.table.map.gridSize*3,y:r.table.map.gridSize*3};touch(r);broadcast(r);break;}
 case 'actor_patch':{if(!assertGm(r,cid,conn))break;const id=actorId(msg.actorId),i=r.table.encounter.actors.findIndex(x=>x.id===id);if(i<0)return sendErr(conn,'Actor not found.','ACTOR_NOT_FOUND');const old=r.table.encounter.actors[i],patch=safeActorPatch(msg.patch),merged={...old,...patch,id:old.id,sourceCharacterId:old.sourceCharacterId,kind:old.kind,clientId:old.clientId,rulesetId:old.rulesetId,health:{...old.health,...(patch.health||{})},resources:{...old.resources,...(patch.resources||{})},combat:{...old.combat,...(patch.combat||{})}};r.table.encounter.actors[i]=actor(merged);if(r.table.encounter.active&&r.table.encounter.phase==='resolution'){refreshExtraActions(r);normalizeResolution(r);}addLog(r,'ACTOR',text(msg.reason||`Updated ${old.name}.`,180),m.name);touch(r);broadcast(r);break;}
 case 'actor_remove':{if(!assertGm(r,cid,conn))break;const id=actorId(msg.actorId);r.table.encounter.actors=r.table.encounter.actors.filter(x=>x.id!==id);delete r.table.positions[id];delete r.table.elevations[id];for(const mm of r.members.values())if(mm.actorId===id)mm.actorId='';touch(r);broadcast(r);break;}
 case 'initiative_set':{const id=actorId(msg.actorId);if(!memberCanMove(r,cid,id))return sendErr(conn,'You cannot set that initiative.','ACTOR_AUTHORITY_REQUIRED');const a=r.table.encounter.actors.find(x=>x.id===id);if(!a)return sendErr(conn,'Actor not found.','ACTOR_NOT_FOUND');a.initiative={...a.initiative,die:msg.die==null?null:num(msg.die,1,1000,1),total:msg.total==null?null:num(msg.total,-99999,99999,0),tieBreakRating:num(msg.tieBreakRating??a.initiative.rating,0,9999,a.initiative.rating)};touch(r);broadcast(r);break;}
 case 'declaration_lock':{const e=r.table.encounter,id=actorId(msg.actorId),cur=currentActor(r),gmOverride=cid===r.ownerId&&!!msg.gmOverride;if(!e.active||e.phase!=='declaration')return sendErr(conn,'Not in declaration phase.','NOT_DECLARATION_PHASE');if(!memberCanMove(r,cid,id)&&!gmOverride)return sendErr(conn,'You cannot declare for that actor.','ACTOR_AUTHORITY_REQUIRED');if(cur?.id!==id&&!gmOverride)return sendErr(conn,'Declarations proceed from slowest to fastest.','OUT_OF_DECLARATION_ORDER');lockDeclarationServer(r,id,msg.declaration||{});addLog(r,'DECLARE',`${r.table.encounter.actors.find(a=>a.id===id)?.name||id} locked a declaration.`,m.name);touch(r);broadcast(r);break;}
 case 'resolution_finish':{const e=r.table.encounter,a=currentActor(r),gmOverride=cid===r.ownerId&&!!msg.gmOverride;if(!e.active||e.phase!=='resolution'||!a)return sendErr(conn,'No actor is resolving.','NOT_RESOLUTION_PHASE');if(!memberCanMove(r,cid,a.id)&&!gmOverride)return sendErr(conn,'You cannot finish that actor’s resolution.','ACTOR_AUTHORITY_REQUIRED');finishResolutionServer(r,msg.outcome==='fizzled'?'fizzled':'resolved',msg.details||{});touch(r);broadcast(r);break;}
 case 'delayed_activate':{const e=r.table.encounter,id=actorId(msg.actorId),idx=e.actors.findIndex(a=>a.id===id),gmOverride=cid===r.ownerId&&!!msg.gmOverride;if(!e.active||e.phase!=='resolution')return sendErr(conn,'Not in resolution phase.','NOT_RESOLUTION_PHASE');if(!memberCanMove(r,cid,id)&&!gmOverride)return sendErr(conn,'You cannot use that delayed action.','ACTOR_AUTHORITY_REQUIRED');if(e.interrupt)return sendErr(conn,'Another interrupt is active.','INTERRUPT_ACTIVE');if(idx<0||!e.delayed.includes(id))return sendErr(conn,'That actor has no available delayed action.','NOT_DELAYED');if(e.resolutionIndex<e.actors.length&&idx>=e.resolutionIndex&&!gmOverride)return sendErr(conn,'Delayed action is not available yet.','DELAY_NOT_AVAILABLE_YET');e.interrupt={actorId:id,type:'delay',returnIndex:e.resolutionIndex};e.declarations[id].status='resolving';syncTurnIndex(e);r.table.movement={actorId:id,round:e.round,spent:0,mode:'half-run',tokenId:'',path:[]};touch(r);broadcast(r);break;}
 case 'defensive_abort_request':{const id=actorId(msg.actorId),d=r.table.encounter.declarations?.[id];if(!memberCanMove(r,cid,id))return sendErr(conn,'You cannot abort for that actor.','ACTOR_AUTHORITY_REQUIRED');if(r.table.encounter.phase!=='resolution'||!d?.locked||['resolved','fizzled','aborted-defense'].includes(d.status))return sendErr(conn,'No unresolved declared action is available to abort.','NO_ACTION_TO_ABORT');d.abortRequest={defenseKind:text(msg.defenseKind||'defense',80),method:['roll','spend'].includes(msg.method)?msg.method:'roll',requestedAt:now(),requestedBy:cid};touch(r);broadcast(r);break;}
 case 'defensive_abort_commit':{if(!assertGm(r,cid,conn))break;const id=actorId(msg.actorId),e=r.table.encounter,d=e.declarations?.[id];if(!d?.locked)return sendErr(conn,'Declaration not found.','NO_DECLARATION');d.abortRequest=null;if(msg.success){d.resolution={...(d.resolution||{}),originalAction:clone(d.action,{}),defenseKind:text(msg.defenseKind||'defense',80),abortAt:now()};d.action={kind:'defend',label:text(msg.label||'Defensive Abort',160),intent:'Aborted declared action to defend.',targetActorId:'',targetFeatureId:'',maneuverId:'',refId:'',payload:{}};d.status='aborted-defense';d.resolvedAt=now();e.delayed=e.delayed.filter(x=>x!==id);if(e.interrupt?.actorId===id)e.interrupt=null;normalizeResolution(r)}else d.resolution={...(d.resolution||{}),abortFailed:true,abortAt:now()};touch(r);broadcast(r);break;}
 case 'encounter_control':{if(!assertGm(r,cid,conn))break;const e=r.table.encounter,op=msg.op;if(op==='start'){sortActors(e,1);startRound(r,1);}else if(op==='next'&&e.active&&e.phase==='resolution')finishResolutionServer(r,'resolved',{});else if(op==='end'){e.active=false;e.phase='free';e.declarationIndex=-1;e.resolutionIndex=-1;e.turnIndex=-1;e.declarations={};e.delayed=[];e.extraActions=[];e.extraActionIndex=0;e.interrupt=null;}else if(op==='previous')return sendErr(conn,'Locked declaration/resolution state cannot be rewound.','LOCKED_ROUND_STATE');e.updatedAt=now();r.table.movement={actorId:'',round:e.round,spent:0,mode:'half-run',tokenId:'',path:[]};touch(r);broadcast(r);break;}
 case 'reveal_show':{if(!assertGm(r,cid,conn))break;const aid=actorId(msg.assetId);if(!r.assets.has(aid))return sendErr(conn,'Reveal asset not found.','ASSET_NOT_FOUND');r.table.reveal={active:true,assetId:aid,name:text(msg.name||r.assets.get(aid).name,160),serial:(r.table.reveal.serial||0)+1,updatedAt:now()};touch(r);broadcast(r);break;}
 case 'reveal_hide':{if(!assertGm(r,cid,conn))break;r.table.reveal={active:false,assetId:'',name:'',serial:(r.table.reveal.serial||0)+1,updatedAt:now()};touch(r);broadcast(r);break;}
 case 'asset_upload':{const a=msg.asset||{},id=actorId(a.id),dataUrl=String(a.dataUrl||'');if(!id||dataUrl.length>MAX_ASSET_DATA||!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/i.test(dataUrl))return sendErr(conn,'Invalid or oversized image asset.','BAD_ASSET');if(cid!==r.ownerId&&!id.startsWith(`token:${cid}:`))return sendErr(conn,'You do not own that image slot.','ASSET_AUTHORITY_REQUIRED');if(!r.assets.has(id)&&r.assets.size>=MAX_ROOM_ASSETS)return sendErr(conn,'Room asset limit reached.','ASSET_LIMIT');const rec={id,kind:text(a.kind||'art',30),name:text(a.name||id,160),dataUrl,updatedAt:now()};r.assets.set(id,rec);for(const mm of r.members.values())if(mm.conn)mm.conn.sendJSON({type:'asset',protocol:PROTOCOL,asset:rec});break;}
 case 'asset_request':{const a=r.assets.get(actorId(msg.assetId));if(a)conn.sendJSON({type:'asset',protocol:PROTOCOL,asset:a});else sendErr(conn,'Asset not found.','ASSET_NOT_FOUND');break;}
 case 'check_request':{if(!assertGm(r,cid,conn))break;const targetId=clientId(msg.request?.targetClientId||msg.targetClientId),targets=targetId==='all'?[...r.members.values()].filter(mm=>mm.clientId!==r.ownerId&&mm.conn):[r.members.get(targetId)].filter(Boolean);if(!targets.length)return sendErr(conn,'No matching player is connected.','CHECK_TARGET_NOT_FOUND');for(const tm of targets){const req=cleanCheckRequest({...msg.request,id:iid('check'),targetClientId:tm.clientId,targetActorId:tm.actorId,requestedBy:cid,requestedAt:now(),status:'open',answer:null});r.sessionTools.checkRequests.push(req);addLog(r,'CHECK',`Requested ${req.label} from ${tm.name}.`,m.name);}r.sessionTools.checkRequests=r.sessionTools.checkRequests.slice(-80);r.sessionTools.updatedAt=now();touch(r);broadcast(r);break;}
 case 'check_answer':{const id=actorId(msg.requestId),req=(r.sessionTools?.checkRequests||[]).find(x=>x.id===id);if(!req)return sendErr(conn,'Check request not found.','CHECK_NOT_FOUND');if(cid!==r.ownerId&&cid!==req.targetClientId)return sendErr(conn,'You cannot answer that check request.','CHECK_AUTHORITY_REQUIRED');req.status='answered';req.answeredAt=now();req.answer={text:text(msg.answer?.text||msg.text,1200),source:text(msg.answer?.source||'core-roller',40),actorId:actorId(msg.answer?.actorId||r.members.get(cid)?.actorId),at:now()};r.sessionTools.updatedAt=now();addLog(r,'CHECK',`${m.name} answered ${req.label}.`,m.name);touch(r);broadcast(r);break;}
 case 'check_dismiss':{const id=actorId(msg.requestId),req=(r.sessionTools?.checkRequests||[]).find(x=>x.id===id);if(!req)return sendErr(conn,'Check request not found.','CHECK_NOT_FOUND');if(cid!==r.ownerId&&cid!==req.targetClientId)return sendErr(conn,'You cannot dismiss that check request.','CHECK_AUTHORITY_REQUIRED');req.status='dismissed';req.answeredAt=now();req.answer=null;r.sessionTools.updatedAt=now();addLog(r,'CHECK',`${m.name} dismissed ${req.label}.`,m.name);touch(r);broadcast(r);break;}
 case 'check_clear':{if(!assertGm(r,cid,conn))break;r.sessionTools.checkRequests=(r.sessionTools.checkRequests||[]).filter(x=>x.status==='open');r.sessionTools.updatedAt=now();touch(r);broadcast(r);break;}
 case 'shared_roll':{const count=num(msg.count,1,100,1),sides=num(msg.sides,2,100,10),roll=cleanSharedRoll({id:iid('roll'),clientId:cid,name:m.name,label:text(msg.label||'Shared roll',160),count,sides,results:Array.from({length:count},()=>crypto.randomInt(1,sides+1)),at:now()});r.sessionTools.sharedRolls.push(roll);r.sessionTools.sharedRolls=r.sessionTools.sharedRolls.slice(-60);r.sessionTools.updatedAt=now();addLog(r,'DICE',`${m.name} rolled ${count}d${sides}: ${roll.results.join(', ')}.`,m.name);touch(r);broadcast(r);break;}
 case 'shared_roll_clear':{if(!assertGm(r,cid,conn))break;r.sessionTools.sharedRolls=[];r.sessionTools.updatedAt=now();touch(r);broadcast(r);break;}
 case 'log_event':{addLog(r,text(msg.kind||'TABLE',60),text(msg.message,1000),m.name);touch(r);broadcast(r);break;}
 case 'leave':{detach(conn);conn.roomCode='';break;}
 default:sendErr(conn,`Unsupported message type: ${text(msg.type,80)}`);
 }}
function frame(op,p=Buffer.alloc(0)){p=Buffer.isBuffer(p)?p:Buffer.from(p);let h;if(p.length<126){h=Buffer.alloc(2);h[1]=p.length}else if(p.length<=65535){h=Buffer.alloc(4);h[1]=126;h.writeUInt16BE(p.length,2)}else{h=Buffer.alloc(10);h[1]=127;h.writeBigUInt64BE(BigInt(p.length),2)}h[0]=0x80|(op&15);return Buffer.concat([h,p])}
function connection(socket){return{socket,buffer:Buffer.alloc(0),frag:null,frags:[],fragBytes:0,isAlive:true,closed:false,roomCode:'',clientId:'',sendJSON(o){if(!this.closed&&!socket.destroyed)socket.write(frame(1,Buffer.from(JSON.stringify(o))))},ping(){if(!this.closed&&!socket.destroyed)socket.write(frame(9))},close(code=1000,reason=''){if(this.closed)return;this.closed=true;const r=Buffer.from(text(reason,120)),p=Buffer.alloc(2+r.length);p.writeUInt16BE(code,0);r.copy(p,2);try{socket.write(frame(8,p))}catch{}setTimeout(()=>{try{socket.end()}catch{}},10)}}}
function parseText(c,s){let msg;try{msg=JSON.parse(s)}catch{return sendErr(c,'Invalid JSON.','BAD_JSON')}if(msg.protocol!==PROTOCOL)return sendErr(c,`Protocol mismatch. Expected ${PROTOCOL}.`,'PROTOCOL_MISMATCH');const cid=clientId(msg.clientId);if(!cid)return sendErr(c,'Missing clientId.','MISSING_CLIENT_ID');if(msg.type==='create_room')return createRoom(c,msg,cid);if(msg.type==='join_room')return joinRoom(c,msg,cid);handle(c,msg,cid)}
function consume(c,chunk){c.buffer=Buffer.concat([c.buffer,chunk]);while(c.buffer.length>=2){const b0=c.buffer[0],b1=c.buffer[1],fin=!!(b0&128),op=b0&15,masked=!!(b1&128);let len=b1&127,off=2;if(!masked)return c.close(1002,'Client frames must be masked');if(len===126){if(c.buffer.length<4)return;len=c.buffer.readUInt16BE(2);off=4}else if(len===127){if(c.buffer.length<10)return;const big=c.buffer.readBigUInt64BE(2);if(big>BigInt(MAX_PAYLOAD))return c.close(1009,'Payload too large');len=Number(big);off=10}if(len>MAX_PAYLOAD||c.fragBytes+len>MAX_PAYLOAD)return c.close(1009,'Payload too large');if(c.buffer.length<off+4+len)return;const mask=c.buffer.subarray(off,off+4);off+=4;const p=Buffer.from(c.buffer.subarray(off,off+len));c.buffer=c.buffer.subarray(off+len);for(let i=0;i<p.length;i++)p[i]^=mask[i&3];if(op===8){c.close();return}if(op===9){if(!c.closed)c.socket.write(frame(10,p));continue}if(op===10){c.isAlive=true;continue}if(op!==0&&op!==1)return c.close(1003,'Only text frames are supported');if(op===1&&!fin){if(c.frag!==null)return c.close(1002,'Unexpected fragmented message');c.frag=1;c.frags=[p];c.fragBytes=p.length;continue}if(op===0){if(c.frag===null)return c.close(1002,'Unexpected continuation');c.frags.push(p);c.fragBytes+=p.length;if(!fin)continue;const full=Buffer.concat(c.frags);c.frag=null;c.frags=[];c.fragBytes=0;parseText(c,full.toString('utf8'));continue}if(op===1&&fin)parseText(c,p.toString('utf8'));}}
const server=http.createServer((req,res)=>{if(req.url==='/health'){res.writeHead(200,{'content-type':'application/json','cache-control':'no-store'});res.end(JSON.stringify({ok:true,protocol:PROTOCOL,version:VERSION,rooms:rooms.size}));return}res.writeHead(426,{'content-type':'text/plain'});res.end('Storyteller d10 room server. Connect with WebSocket.');});
server.on('upgrade',(req,socket,head)=>{const origin=req.headers.origin||'';if(ALLOWED_ORIGINS.length&&!ALLOWED_ORIGINS.includes(origin)){socket.write('HTTP/1.1 403 Forbidden\r\n\r\n');return socket.destroy()}const key=req.headers['sec-websocket-key'];if(!key||req.headers['sec-websocket-version']!=='13'||String(req.headers.upgrade||'').toLowerCase()!=='websocket'){socket.write('HTTP/1.1 400 Bad Request\r\n\r\n');return socket.destroy()}const accept=crypto.createHash('sha1').update(key+'258EAFA5-E914-47DA-95CA-C5AB0DC85B11').digest('base64');socket.write('HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Accept: '+accept+'\r\n\r\n');const c=connection(socket);socket.setNoDelay(true);socket.on('data',x=>consume(c,x));socket.on('close',()=>{c.closed=true;detach(c)});socket.on('error',()=>{c.closed=true;detach(c)});if(head?.length)consume(c,head)});
const heartbeat=setInterval(()=>{for(const r of rooms.values())for(const m of r.members.values())if(m.conn){if(m.conn.isAlive===false){try{m.conn.socket.destroy()}catch{};continue}m.conn.isAlive=false;m.conn.ping()}const cutoff=now()-ROOM_TTL_MS;for(const[code,r]of rooms)if(![...r.members.values()].some(x=>x.conn)&&(r.emptyAt||r.updatedAt)<cutoff)rooms.delete(code)},30000);
function shutdown(){clearInterval(heartbeat);server.close(()=>process.exit(0));setTimeout(()=>process.exit(0),1000).unref()}
process.on('SIGINT',shutdown);process.on('SIGTERM',shutdown);server.listen(PORT,HOST,()=>console.log(`Storyteller d10 room server v${VERSION} listening on ws://${HOST}:${PORT} (protocol ${PROTOCOL})`));
